name: Test
on: [push]
jobs:
    Test_gcc:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - run: sudo apt update -y
        - run: sudo apt install -y cmake
        - run: cmake -H. -B_build -DBUILD_TESTS=ON
        - run: cmake --build _build
        - run: echo "This job's status is ${{ job.status }}."

    Test_clang:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - run: sudo apt update -y
            - run: sudo apt install -y clang cmake
            - run: cmake -H. -B_build -DBUILD_TESTS=ON
            - run: cmake --build _build
            - run: echo "This job's status is ${{ job.status }}."
