name: Test
on: ["push", "pull_request"]
jobs:
    Test_gcc:
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - run: git submodule init && git submodule update
        - run: sudo apt update -y
        - run: sudo apt install -y cmake
        - run: cmake -H. -B_build -DBUILD_TESTS=ON
        - run: cmake --build _build
        - run: cmake --build _build --target test
        - run: _build/check
        - run: cmake --build _build --target test -- ARGS=--verbose
        - run: echo "This job's status is ${{ job.status }}."        
        - name: Do lcov stuff
        - run: lcov -c -d build/CMakeFiles/banking.dir/banking/—include*.cpp —output-file./coverage/lcov.info
        - name: Publish to coveralls.io
          uses: coverallsapp/github-action@v1.1.2
          
          
    Test_clang:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v3
            - run: git submodule init && git submodule update
            - run: sudo apt update -y
            - run: sudo apt install -y clang cmake
            - run: cmake -H. -B_build -DBUILD_TESTS=ON
            - run: cmake --build _build
            - run: cmake --build _build --target test
            - run: echo "This job's status is ${{ job.status }}."
